control:
  # Начальные значения скоростей
  initial_speed: 0.5
  initial_turn: 1.0
  
  # Таймаут при отсутствии сообщений (в секундах)
  timeout_threshold: 0.2
  
  # Интервал проверки таймаута (в секундах)
  check_interval: 0.1
  
  # Привязки клавиш
  move_bindings:
    i: [1, 0, 0, 0]
    o: [1, 0, 0, -1]
    j: [0, 0, 0, 1]
    l: [0, 0, 0, -1]
    u: [1, 0, 0, 1]
    ',': [-1, 0, 0, 0]
    '.': [-1, 0, 0, 1]
    m: [-1, 0, 0, -1]
    O: [1, -1, 0, 0]
    I: [1, 0, 0, 0]
    J: [0, 1, 0, 0]
    L: [0, -1, 0, 0]
    U: [1, 1, 0, 0]
    '<': [-1, 0, 0, 0]
    '>': [-1, -1, 0, 0]
    M: [-1, 1, 0, 0]
    t: [0, 0, 1, 0]
    b: [0, 0, -1, 0]
  
  # Привязки клавиш для изменения скорости
  speed_bindings:
    q: [1.1, 1.1]
    z: [0.9, 0.9]
    w: [1.1, 1]
    x: [0.9, 1]
    e: [1, 1.1]
    c: [1, 0.9]